### ISSUE TITLE
Incompatibility with color package

### ISSUE THREAD

**Issue by mgmillani** [schnorr/iiufrgs#28]
If we try to use the color package, we get erros like:

    ! Undefined control sequence.
    \set@color ...\@pdfcolorstack push{\current@color
                       }\aftergroup \reset@color 
    l.113 \begin{document}

This also happens with todonote.

**Comment by mgmillani** [comment]
The solution might be [here](http://tex.stackexchange.com/questions/102927/undefined-control-sequence-with-color-package-in-custom-latex-document-class).

**Comment by matthiasdiener** [comment]
The workaround I use is to load the color/xcolor packages before the class:

    \RequirePackage[table]{xcolor}
    \documentclass[ppgc,tese,english,openright]{iiufrgs}

But fixing the bug would be much nicer obviously.

**Comment by fgiacomel** [comment]
Thanks for the workaround, Matthias. I had the same problem with the colortbl package. Added \RequirePackage{colortbl} before \documentclass and it worked like a charm.

**Comment by maylermartins** [comment]
Another possible solution:

%\RequirePackage[tocindentauto,tocfullflat]{tocstyle}
\RequirePackage[usenames,dvipsnames,svgnames,table]{xcolor}
\RequirePackage[tocindentauto,tocfullflat]{tocstyle}
