### ISSUE TITLE
Sections are not numbered

### ISSUE THREAD

**Issue by schnorr** [schnorr/iiufrgs#36]
After having upgraded by debian system, sections, subsections and subsubsections are not being numbered in the text. They correctly appear numbered in the table of contents, but not in the text. I have made a very small package that show the problem (see the PDF within). Link:
https://dl.dropboxusercontent.com/u/1119921/iiufrgs_problem.tar.gz
Does anyone have the same problem? I believe is something related to the titlesec package.

**Comment by schnorr** [comment]
To get back the correct numbering, I had to comment out the cls part that configures the section and comment the titlesec package. Perhaps my version of titlesec is buggy. Anyone can replicate this?

**Comment by mgmillani** [comment]
I'm using Arch Linux and it works fine for me (tested with your example).
My pdflatex version is `pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Arch Linux)`, titlesec version is `[2011/12/15 v2.10.0 Sectioning titles]`.

**Comment by kassick** [comment]
Fedora seems to have no issue either (pdftex and xetex)
pdfTeX 3.14159265-2.6-1.40.15 (TeX Live 2014)
XeTeX 3.14159265-2.6-0.99991 (TeX Live 2014)
titlesec.sty:
>     % This file is part of the titlesec distribution release 2.10.0
>     % -----------------------------------------------------------
(/usr/share/texlive/texmf-dist/tex/latex/titlesec/titlesec.sty
Package: titlesec 2011/12/15 v2.10.0 Sectioning titles

I'm sending my tex-dist's titlesec folder. Lucas, please do a M-x diff on
the sty (and all other files) between debian's dist  and the ones I've sent
you.

Kassick.


Em sex, 20 de mai de 2016 às 18:40, Marcelo Garlet Millani <
notifications@github.com> escreveu:

**Comment by schnorr** [comment]
Thanks everyone for checking this. My debian's version of titlesec is 2.10.1.
Ctan reports they have already released a new version:
https://www.ctan.org/pkg/titlesec?lang=en
So, the fix is to avoid the version 2.10.1.

**Comment by jtoss** [comment]
Hello, section numbering were not showing in the text headings.
I had to uncomment lines related to \section format in iiufrgs.cls to get them back working.

@schnorr  I'm also using  v2.10.1 of titlesec , doesn't seems to be the issue. 

>  titlesec.sty    2016/03/15 v2.10.1 Sectioning titles 
> pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian)
