### ISSUE TITLE
As seções não estão sem numeração. Isso está correto?

### ISSUE THREAD

**Issue by petrillo** [schnorr/iiufrgs#37]
Usando o iiufrgs.cls, os seções não estão sendo numeradas. Analisando o arquivo, vi que o comando 
%\renewcommand{\section}{
         \@startsection{section}{2}{0pt}{18pt}{18pt}{\reset@font\normalsize\bfseries}
}

está comentado. 

Retirando o marcador de comentário (%), a numeração fica correta. Sendo assim, está correto as seções não estarem sendo numeradas?

**Comment by mgmillani** [comment]
Acabei de compilar o arquivo exemplos/cic-tc.tex e as seções estão sendo numeradas.

O problema ocorre para ti também com os arquivos de exemplo?

**Comment by quitaiskiluisf** [comment]
Não seria o mesmo problema que foi relatado em #36?
